Promise.length = {};
Promise.name = {};
Promise.prototype = {};
Promise.all = {};
Promise.race = {};
Promise.resolve = {};
Promise.reject = {};
Promise();
Promise.all();
Promise.race();
Promise.resolve();
Promise.reject();
