String.length = {};
String.name = {};
String.prototype = {};
String.fromCharCode = {};
String.fromCodePoint = {};
String.raw = {};
String();
String.fromCharCode();
String.fromCodePoint();
String.raw();
